### ISSUE TITLE
Automate the process of creating a baseimage

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-platform#17]
*Why?*
if we lose the image, we need to recreate it. since it was done by hand, it will be hard. Like we need to remember what packages were installed, which user was created etc.

*Done when*
We can rebuild the baseimage with a single command.

*Original notes*
we need something that creates our baseimage.
that image gets copied and modified to become our output images. but the baseimage was once created with virt-install. that part is not automated yet.

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.
