### ISSUE TITLE
Pixelated packages are not updated automatically, i.e. for security fixes

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-platform#21]
This is probably too early to implement, but at some time we need a way to automatically install security fixes, and we could use unattended-upgrades for it, like leap does.

Before we need to make sure that we also have multiple repositories, so we have a production one that only recieves security updates.

**Comment by bwgpro** [comment]
Is this fixed by the unattended upgrades we now have? @fbernitt @varac

**Comment by cz8s** [comment]
it is fixed and works
