### ISSUE TITLE
users should be able to customize their instance

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-platform#29]
the images we build have a configuration with a hardcoded
ip in the leap configuration. That makes 'leap deploy' fail.
We should come up with a way to avoid hardcoded ips

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.
