### ISSUE TITLE
Make nagios less noisy

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-platform#37]
We should tweak nagios so it only sends out notifications on important failures.

**Comment by varac** [comment]
i tamed nagios quite a bit, it's 4-5 msgs/day in average.
see https://groups.google.com/a/thoughtworks.com/forum/?hl=en#!groupsettings/pixelated-cron for an overview on last-weeks activity.

**Comment by bwgpro** [comment]
Blocked by pixelated-project/project-issues#13
