### ISSUE TITLE
Allow try.pixelated to be used for testing with some selected external domains

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-platform#38]
Why: Be able to test emailing external domains.
Done: When we can send emails form try.pixelated to an arbitrary domain.

Whitelist recipients/domain so try.pixelated can send outgoing mail for testing and for nagios notifications

**Comment by cz8s** [comment]
which domains should be whitelisted?
we can add them to a file and use postfix 
and transport_maps to achieve this

**Comment by cz8s** [comment]
added thoughtworks.com the whitelist.
To add more domains, add them to /etc/postfix/transport and do a 
'postmap /etc/postfix/transport'

**Comment by varac** [comment]
i move this out of QA because this is not a permanent solution, every puppetrun would revert this change atm. we have #47 to make these changes permanent by adding this to a custom pixelated class that only get applied by us.

**Comment by varac** [comment]
btw, nagios mails work now
