### ISSUE TITLE
  install/configure unattended upgrades for pixelated packages

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-platform#41]
## Why
Having old version of packages and libraries create security holes in our software. In the other hand admins should not have to update our software manually, at it is laborious and error-prone. Having unattended-upgrades set up correctly help to automatically push our releases to all installations.

## Definition of done
Newer releases of the components we use are installed automatically within 24hrs. We get a warning if one of this upgrades breaks our own installation (including functional tests).

**Comment by cz8s** [comment]
why:  admins should not have to update our software manually. Having unattended-upgrades set up correctly help to automatically push our releases to all installations

definition of done: unattended-upgrades is installed with our puppet scripts and is configured to automatically install new packages from our repository

**Comment by lqust** [comment]
I have updated the description and moved this to ready. @varac and @cz8s: Thanks for your help! Please check if the description works (I have tweaked the definition of done a bit to focus on the desired outcome)

**Comment by fbernitt** [comment]
See http://blog.ezyang.com/2010/03/third-party-unattended-upgrade/ for inspiration

**Comment by tiagoferraz** [comment]
How this could be QA'ed?

**Comment by fbernitt** [comment]
Given I have a pixelated provider vagrant box (created from vanilla debian using the convert-to-pixelated.sh script)
And I wait till a new dispatcher package is created (the build pipeline for the dispatcher is completed with a new run and green)
And I log into the vagrant box as root
And I run unattended-upgrades --dry-run -d 
Then it should show that it would update the pixelated-dispatcher package
