### ISSUE TITLE
shorewall and docker don't like each other

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-platform#44]
when restarting shorewall it drops the iptables rules
that were added by docker

**Comment by cz8s** [comment]
here is a solution that should work:

http://serverfault.com/questions/579726/docker-shorewall

**Comment by cz8s** [comment]
Problem we have now is that the DOCKER chain is deleted by 'shorewall restart' and then docker
does not work anymore. We need to tell shorewall to leave the DOCKER chain alone

**Comment by cz8s** [comment]
the way to go forward is to tell docker not to do any networking and let shorewall do the heavy lifting.
I don't know how portforwding will work then. Spiking now ...

**Comment by fbernitt** [comment]
I found one potential solution for this problem: The docker daemon has an option --iptables that can be set to false. To test it, I changed the /etc/default/docker to

```
...
DOCKER_OPTS="--iptables=false"
...
```
After restarting docker its still possible to start user agents, but docker launches extra proxies to forwared the traffic

```
ps ax|grep docker-proxy
30313 ?        Sl     0:00 docker-proxy -proto tcp -host-ip 127.0.0.1 -host-port 5001 -container-ip 172.17.0.2 -container-port 4567
```

This solution has a resource drawback, but with it shorewall and docker should work fine together.
