### ISSUE TITLE
Add custom pixelated puppet class that is only used on our installations

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-platform#47]
We have some customizations, such as test users and whitelisted recipient domains (#38), that we don't want to apply by default, because other ppl might use pixelated-platform as well.

**Comment by varac** [comment]
just as clarification:

-  " You can create custom puppet modules under files/puppet. The custom puppet entry point is in class ‘custom’ which can be put into files/puppet/modules/custom/manifests/init.pp. This class gets automatically included by site_config::default, which is applied to all nodes." - from  https://leap.se/en/docs/platform/faq#How.can.i.customize.the.leap_platform.puppet.manifests..
- we use this method of customizing in the pixelated-platform, custom/manifests/init.pp. this class is used to customize leap_platform with the pixelated dispatcher setup, so this is general purpose for all users that install pixelated platform.

so we would need another layer of including custom configs

**Comment by varac** [comment]
i.e. custom/manifests/init.pp could check if a certain class is present, and if so, include it - just like leap_platform does.

**Comment by lqust** [comment]
try.pixelated-project.org also have a text box with instructions and test mail contacts that we should not distribute with the rest of the code. Can it be covered by this as well?

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.
