### ISSUE TITLE
add option to rename the platform

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-platform#48]
when we build the platform, its name is always
try.pixelated-project.org
But when users download our images or if we deploy to
staging, we need to change the name to the actual hostname.
This involves changing ssl certs and the config.

**Comment by cz8s** [comment]
workflow:

* change domain in provider.json
* regenerate certs
* run leap deploy

**Comment by cz8s** [comment]
Added acpid to install in the ci-config.
Commit 7947cc4591bc17b6a0044f9227e92bfb00024182

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.
