### ISSUE TITLE
use inter.net mirror on all our servers

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-platform#50]
building and upgrading should be much faster.

**Comment by cz8s** [comment]
@fbernitt: do you have a url for the inter.net debian mirror?

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.
