### ISSUE TITLE
configure check_mk only if the node has the tag 'monitoring'

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-platform#55]
```leap deploy``` tries to configure check_mk 
But if the node was deployed without the 'monitoring' flag,
this fails

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.
