### ISSUE TITLE
automate deploy to live (try.pixelated-project.org)

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-platform#57]
try.pixelated uses old versions of our software.
I am very interested in having the data in a seperated
directory. Maybe we should deploy staging to prod(try)
sooon

**Comment by cz8s** [comment]
I want to take the opportunity to automate the steps to deploy a new version to live.
We need to keep the data if we deploy a new version. This means:
* Have /var/lib/pixelated on a dedicated partition
* Have /home/leap/configuration on a dedicated partition and run 'leap deploy' after deploy
* Have a backup of the couddb databases and restore them after deploy

**Comment by cz8s** [comment]
new partition on try: All data is now under /storage:
```
root@pixelated:/var/lib/pixelated# ls /storage/
bigcouch_data  dispatcher_data	leap_configuration
```

I change the root in /etc/default/pixelated-dispatcher-manager to point to /storage/dispatcher_data
and set a link for bigcouch and leap_configuration:
```
root@pixelated:/var/lib/pixelated# ls -l /opt/bigcouch/var/lib /home/leap/configuration
lrwxrwxrwx 1 root root 27 Feb 19 14:39 /home/leap/configuration -> /storage/leap_configuration
lrwxrwxrwx 1 root root 23 Feb 19 14:34 /opt/bigcouch/var/lib -> /storage/bigcouch_data/
```

**Comment by cz8s** [comment]
while testing I ran across the error of bigcouch not working because of multiple nodes entries:
```
err: /Stage[main]/Site_couchdb::Bigcouch::Settle_cluster/Exec[settle_cluster_membership]/returns: change from notrun to 0 failed: /srv/leap/bin/run_tests --test CouchDB/Is_cluster_membership_ok? --retry 12 --wait 10 returned 2 instead of one of [0] at /srv/leap/puppet/modules/site_couchdb/manifests/bigcouch/settle_cluster.pp:10
```
I have a way to manually fix this and wanted to write it down somewhere so we can find it again:

1: find out which nodes are configured:
```
# curl localhost:5984/_membership
{"all_nodes":["bigcouch@pixelated.asdflkj.tld"],"cluster_nodes":["bigcouch@pixelated.asdflkj.tld","bigcouch@pixelated.try.pixelated-project.org"]}
```

2: find out revision of node you want to delete:
```
# curl localhost:5986/nodes/bigcouch@pixelated.asdflkj.tld
{"_id":"bigcouch@pixelated.asdflkj.tld","_rev":"1-967a00dff5e02add41819138abb3284d"}
```
3: delete entry:
```
# curl -X DELETE "localhost:5986/nodes/bigcouch@pixelated.asdflkj.tld?rev=1-967a00dff5e02add41819138abb3284d"
{"ok":true,"id":"bigcouch@pixelated.asdflkj.tld","rev":"2-eec205a9d413992850a6e32678485900"}
```

**Comment by lqust** [comment]
Waiting for Christoph to be back

**Comment by cz8s** [comment]
first two steps are in the pipeline.\
The pipeline does not start automatically and only prepares the image and does 
not actually change try.pixelated yet

**Comment by lieblingswelt** [comment]
while the pipeline was green, it failed to start docker. I have changed the script so it now fails on errors. Yet we still need to find out why leap deploy cannot start docker.
