### ISSUE TITLE
[leap] Bigcouch database disk usage should not grow when no new mails are added

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-platform#60]
# Steps to reproduce

- Deploy leap platform from scratch for the first time on a fresh debian stable server.
- Wait and watch Bigcouch database disk usage over time

# Expected result

- Bigcouch database disk usage should stay the same
    
# Actual result

- Without recieving mails to any account, the Bigcouch database disk usage is growing because

see https://leap.se/code/issues/6725

**Comment by lqust** [comment]
Waiting for Eilijah tests on big couch

**Comment by varac** [comment]
@re-nobre besides all of us are are bit sloppy with this, we decided that if block an issue we should add a comment *why* this get blocked, so we know the current state.
it turned out that there was a merge req. pending that @cz8s wanted to look in, so there was no reason to block this (but it was linked in the leap issue tracker, see the link in the descr.)

**Comment by varac** [comment]
re-blocked, depending on https://github.com/pixelated-project/project-issues/issues/44

**Comment by varac** [comment]
ok, i waited a bit for QA, so we have some weeks to investigate.

both the disk usage for the [root fs of dev.pix](https://unstable.pixelated-project.org/pnp4nagios/index.php/graph?host=dev1.dev.pixelated-project.i&srv=fs_/) and the [storage partition on unstable.pix](https://unstable.pixelated-project.org/pnp4nagios/index.php/graph?host=unstable1.unstable.pixelated-project.i&srv=fs_/storage) show a very stable level, which is not or just very marginally increase over the last weeks.

**Comment by tiagoferraz** [comment]
Based on the comments from @varac , this issue was closed. If in another deploy we perceive bigcouch disk usage grows we reopen the issue, or create a new issue.
