### ISSUE TITLE
as an admin I want to choose on which box the dispatcher gets installed

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-platform#62]
this is a problem for multi-host leap setups.
At the moment the dispatcher gets installed on _all_ of them. We need to be able to choose just one of them.
The way to do it the leap way is to tag that host in the leap configuration and then our puppet scripts are only applied on that host.

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.
