### ISSUE TITLE
As someone who wants to try pixelated I want a curl install.sh bootstrap script

### ISSUE THREAD

**Issue by fbernitt** [pixelated-project/pixelated-platform#63]
Background:

Currently the setup of a new pixelated/leap provider contains a lot of manual steps. To make creating a test installation really easy I would like to have a script that bootstraps a pixelated installation from a vanilla debian.

Requirements

When I have a vanilla debian stable server
And I execute 'curl https://raw.githubusercontent.com/pixelated-project/pixelated-platform/master/install.sh | /bin/bash' as root on it
And wait for quite a while
Then I have a running pixelated provider

**Comment by tiagoferraz** [comment]
@fbernitt what I should verify to make sure pixelated platform is installed correctly?

**Comment by bwgpro** [comment]
The install script is failing if we don't export the LC_ALL=en_US.UTF-8 beforehand, that can be easily fixed
The biggest problem now is that it breaks on the following line. I tried to run ntpdate by hand and some other things but I could not manage to get past this.

```
- running ntpdate...
  - [pixelated.pix.example.org]  9 Mar 21:29:54 ntpdate[28366]: no server suitable for synchronization found

- error Capistrano::CommandError: failed: "sh -c 'test -f /usr/sbin/ntpdate && ntpdate 0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org'" on pixelated.pix.example.org
```


Any ideas @fbernitt ?

**Comment by jeffersonhsta** [comment]
The problem to use ntpdate is our firewall.

Script install.sh was tested and it's working, but is necessary do some changes for it

* Set environment variable LC_ALL=en_US.UTF-8
* After run install.sh, and run "leap test" shown an error that was solved restarting Apache2
* Is necessary add Vagrant port forward 4430 -> 4430, for access Leap web application to manage Leap account.

@fbernitt any questions, feel free to ask me.

**Comment by jeffersonhsta** [comment]
@fbernitt I am wondering about should we have a Vagrantfile on pixelated-platform repo?
I think would be better than have this one on readme file.

I also thinking about put on readme file that is good have environment viable LC_ALL defined before run install script.

**Comment by fbernitt** [comment]
@jeffersonhsta For me a Vagrantfile would be a good thing. About the LC_ALL variable...perhaps we should just add a check for it into the setup procedure and fail with a good error message? Instead of forcing users to have to read this?

**Comment by bwgpro** [comment]
Maybe we should set it in the start of the script? I think we shouldn't
change the values permanently, so having this on the beginning of the run
may be a good thing.

Bruno W.G.
bwgpro@gmail.com

**Comment by jeffersonhsta** [comment]
@fbernitt I think we don't need fail if LC_ALL are undefined, but put on readme file that would be better have this variable defined is enough, what do you think about it?

About the Vagrantfile I will commit the file that I used.

**Comment by bwgpro** [comment]
It actually breaks a lot of steps when we don't have that defined.

Bruno W.G.
bwgpro@gmail.com

**Comment by fbernitt** [comment]
I would be happy with the variant that we set it to something good if it has not been set by the user. Problem is: The locale we choose should better be available on the system... that might not be always the case... otherwise it might fail with again different error messages
