### ISSUE TITLE
Explain as easily as possible how to get started working with the Pixelated Platform

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-platform#65]
## Why
In order to have more contributions we need to make it easy for contributors and potential users to set up their platform instances

## Definition of done
* There is a getting started guide that works for the platform
* There is a process in place to keep the getting started guide up to date
* Any steps that are deemed 'too hard' right now have stories to automate/simplify them

**Comment by lieblingswelt** [comment]
I think dc348c47474c137864163d36135f7e264f89fd94#diff-04c6e90faac2675aa89e2176d2eec7d8 and 9da1c93e164653fb2983f29b894934c34389e4da#diff-04c6e90faac2675aa89e2176d2eec7d8 are related to this.

**Comment by lieblingswelt** [comment]
Feedback by a developer trying to set up the platform from the README:
- vagrant:  error asks to run vagrant init which then creates vagrantfile.
- change wording to make clear that Leap configuration paths are alternatives (with version control, without version control)
- is a step missing? understand why configuration of node is already done.
- Installing Pixelated on the LEAP provider node: note that it is important to rerun leap deploy and leap test after every config change
- make clear that installation is finished before trouble shooting section starts.
- access localhost: port mapping missing
- Installation option via wget mark clearly as alternative!
- Installation via wget: mark as currently broken
- fingerprint mismatch troubleshooting

**Comment by GavinSchalliol** [comment]
(Adding myself as a participant to get notifications)

**Comment by rafaelzlisboa** [comment]
i have two comments:
- i thought `./convert-to-pixelated.sh` was the easiest way to get this up and running. if yes, what about we move it to the top of the README?
- should we rename "convert to pixelated" to something more intuitive such as install/download/setup? i understand that it might be a very intrusive setup (i.e. takes over port 80 etc), but maybe that's something we could solve with user messaging or warnings instead of the name of the script...

**Comment by apretto** [comment]
I agree with both your points. :+1:

**Comment by neissi** [comment]
Thanks for the comments!!!
Tomorrow morning a techops member will sit with us and try execute steps from Read me.
whether everything is ok, we can launch it.

**Comment by neissi** [comment]
Fernanda Martins(Techops), will try again today. 
as soon as she finish, we can launch it.

**Comment by neissi** [comment]
Fernanda gave me a feedback, she execute all steps and looks like that everything is ok.
