### ISSUE TITLE
Nagios mails end up wrongly in vmail mailspool

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-platform#67]
## Steps to reproduce
* Have a staging build pass
* Log into the machine 
* Do a `ls` on the folder /var/mail/vmail/Maildir/new

## Expected result
You do not see any nagios files

## Actual result
```
root@pixelated:/var/mail/vmail/Maildir/new# grep From  *
1425986886.Vfe01I82540M412233.pixelated:From: nagios@pixelated.try.pixelated-project.org
1425988531.Vfe01I827a1M436921.pixelated:From: nagios@pixelated.staging.pixelated-project.org
1425988661.Vfe01I8279fM300531.pixelated:From: nagios@pixelated.staging.pixelated-project.org
1425989011.Vfe01I827b4M466837.pixelated:From: nagios@pixelated.staging.pixelated-project.org
1425995861.Vfe01I82725M981416.pixelated:From: nagios@pixelated.staging.pixelated-project.org
```

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.
