### ISSUE TITLE
[LEAP] Leap_mx should only be started once on platform deploy

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-platform#69]
# Steps to reproduce

Deploy leap platform from scratch for the first time on a fresh debian stable server

# Expected result

Leap_mx is started once during deploy
    
# Actual result

Leap_mx is started twice during deploy

see https://leap.se/code/issues/6706#note-4 for details

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.
