### ISSUE TITLE
Build Vagrant libvirt/kvm Image

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-platform#7]
and automate build using a go pipeline

**Comment by varac** [comment]
@lqust: right now, we build a vagrant box for the (default) virtualbox provider. i'd like to have a libvirt/kvm image as well, and it can be done easily with [vagrant-mutate](https://github.com/sciurus/vagrant-mutate)

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.
