### ISSUE TITLE
LEAP Platform Commits should be syntax checked and linted locally

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-platform#70]
# Steps to reproduce

- commit and try to push a leap platform change with syntax errors

# Expected result

- you shall not push !

# Actual result

- the next puppetrun on the given client will fail

**Comment by varac** [comment]
I documented how to use a pre-commit for syntax and style guide checking: https://github.com/leapcode/leap_platform#contributing

After QA, i'll send a mail around.

**Comment by varac** [comment]
please hold on, i'm moving the repository

**Comment by varac** [comment]
ok, please use the instructions at https://github.com/pixelated-project/puppet-git-hooks#installation

**Comment by tiagoferraz** [comment]
It is working. Would be good to list the per-requirements here and link this document to a "How Contribute" for Platform.
