### ISSUE TITLE
HowTo run this on amazon?

### ISSUE THREAD

**Issue by fbernitt** [pixelated-project/pixelated-platform#71]
A small howto that covers how to run a pixelated provider in the amazon cloud. Even though this is not are target environment, it might make it easier for people to try it out.

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.
