### ISSUE TITLE
test if mails can be removed

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-platform#73]
## why
I want to be sure that the user-agent can delete mails and it is nice to clean up after all tests.

## definition of done
after the tests have run, I can login as behave-user on staging and will not see any mail

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.
