### ISSUE TITLE
Nagios should allow host/service acknoledgements

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-platform#80]
atm, there's no option to acknoledge a service in https://wazokazi.is/nagios3/ or https://unstable.pixelated-project.org/nagios3/

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.
