### ISSUE TITLE
[LEAP] leap-mx 0.6 should deliver mail when started with missing mailspool directory

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-platform#81]
see https://leap.se/code/issues/6856#change-39906 for details

**Comment by tiagoferraz** [comment]
This is closed on Leap, could we close this?

**Comment by varac** [comment]
i'll way a day until @cz8s can reproduce this error. 
then, the expected behaviour would be:

* trigger a deploy of staging
* register a user
* connect with the useragent to generate a key
* send one mail to this user
* restart leap_mx
* from now on, new mails should be processed fine.

**Comment by varac** [comment]
blocked because current staging is failing 
http://go.dfi.local:8153/go/tab/pipeline/history/staging.pixela

**Comment by cz8s** [comment]
still failing because the directory is missing again ...

**Comment by varac** [comment]
fixed by adding this to pixelated-platform/buildscripts/configure-leap.sh:

```
# leap-mx needs to get restarted after the first incoming mail is delivered (#6687)
# https://github.com/leapcode/leap_mx#060
[ -d /var/mail/vmail/Maildir/new ] || ( mkdir -p /var/mail/vmail/Maildir/new; chmod 700 /var/mail/vmail/Maildir/new; chown -R vmail:vmail /var/mail/vmail/Maildir/ )
/etc/init.d/leap-mx restart

```

**Comment by varac** [comment]
after finalizing the above dirty fix on May 6, we didn't experienced any leap_mx hickups anymore. Let's close this until further notice.
