### ISSUE TITLE
enable tls in docker

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-platform#82]
## why

we should encrypt every communication. The communication between dispatcher-manager and docker is not encrypted at the moment. Its not urgent because there are no credentials transmitted and everything is on the same server, but we need to enable tls before we can scale

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.
