### ISSUE TITLE
[Nagios] should not complain about a 10GBit network interface

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-platform#85]
we get this on wazokazi.is:

```
root@pixelated:~# ncli -z '!o' -g production

Interface 4           WARNING WARN - [vetha6b5] (up) 10.00GBit/s (wrong speed, expected: 100MBit/s)(!), in: 0.72B/s(0.0%), out: 1.10B/s(0.0%)
```

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.
