### ISSUE TITLE
[Nagios] should be able to send mail notifications

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-platform#87]
right now, postfix on try.pix is configured to *not* send out mails to other domains than to pixelate-project.org, so nagios mails end up bouncing in the leap_mx spooldir.

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.
