### ISSUE TITLE
[Nagios] Check_mk logwatch should check logfiles in /var/log/pixelated/

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-platform#88]

**Comment by varac** [comment]
see https://github.com/pixelated-project/pixelated-platform/issues/45

**Comment by varac** [comment]
see also: https://github.com/pixelated-project/pixelated-dispatcher/issues/98

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.
