### ISSUE TITLE
Build for external packages

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-platform#9]
we provide some packages which are not from us but which are needed by our packages and are not in debian stable. We need to build these packages from source. A buildd would be nice for that

**Comment by dudadornelles** [comment]
How are we gonna go about this?

**Comment by cz8s** [comment]
we should wait until we know which packages we really need and then set up a go pipeline to build and deploy these packages.
But I would wait a little before starting with this job

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.
