### ISSUE TITLE
Evaluate couchdb 1.6 usage for platform

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-platform#91]

**Comment by varac** [comment]
see also #51

**Comment by varac** [comment]
i wanted to create a new instance on pix-master2 with foreman, but this is currently broken (https://github.com/pixelated-project/project-issues/issues/109). i'm marking this as blocked.

**Comment by varac** [comment]
i'm removing the `blocked` label because i started developing couch1.6 locally now.

**Comment by varac** [comment]
waiting for #97

**Comment by varac** [comment]
to QA you could use:

```
git clone --branch couch16 --recursive gitlab_sa@git.thoughtworks.net:pixelated/pixelated-platform-environments.git
cd pixelated-platform-environments/pixelated-project.org
leap local start couch16
leap node init couch16
leap deploy couch16
sudo echo '10.5.5.2  couch16.local.pixelated-project.org couch16 api.local.pixelated-project.org local.pixelated-project.org' >> /etc/hosts
```
and then you should have a vagrant node running the platform, the webapp should be at https://local.pixelated-project.org/

**Comment by varac** [comment]
also, couchdb should be installed on the node:
```
--- pixelated-platform-environments/pixelated-project.org ‹couch16* M› » leap ssh couch16      
Warning: Permanently added '10.5.5.2' (ECDSA) to the list of known hosts.
Linux leap-wheezy 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
root@couch16:~# dpkg -l|grep couch
ii  couchdb                            1.6.0+dfsg.1-1~leap70+1                             amd64        RESTful document oriented database
ii  python-couchdb                     0.8-1                                               all          library for working with Apache CouchDB

```

and `leap test` should succeed:

**Comment by neissi** [comment]
I followed steps to doing QA, but:
- when I run "leap local start couch16" the output was: -bash: leap: command not found. To solve this I installed the leap-cli (gem install leap-cli) and run again, now the output was: Could not find command "local".
I'm using: Name: leap_cli / Version: 1.7.3
@varac could you help on that? Are missing something? Thanks.

**Comment by varac** [comment]
@neissi the right gem is called leap_cli - from the gem install cmd it looks like you  installed "leap-cli".
could you paste the output of 

```
gem list | grep leap
leap --version
```

please ?

**Comment by neissi** [comment]
Thanks @varac 

I removed the wrong gem, and installed the right one (leap_cli).
leap_cli-1.7.3.gem
Version: 1.7.3
===============================================================================

I tried run "leap local start couch16" and the output was: leap local start couch16
 = This leap command (v1.7.3) is not compatible with the platform /Users/nlima/dev/pixelated-platform-environments/leap_platform (v0.6).
   You need either leap command 1.6.1 to 1.99 or platform version 0.7 to 0.99
 = bailing out

After this output I changed to: Name: leap_cli Version: 1.6.2 and the problem now is when I run 
" leap node init couch16" I've a problem with ntp (I run inside vpn): running ntpdate...
     - [couch16.local.pixelated-project.org] 24 Jun 20:25:35 ntpdate[6277]: no server suitable for synchronization found
    - error Capistrano::CommandError: failed: "sh -c 'test -f /usr/sbin/ntpdate && ntpdate 0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org'" on couch16.local.pixelated-project.org

**Comment by varac** [comment]
sorry @neissi i pushed to the couch16 branch again, so it now uses the latest develop branch of leap_platform, please try the steps above again.

@shyba said that ntp is blocked, i hope using the latest platform that i just pushed should cope with that - if not, please tell me.

**Comment by neissi** [comment]
Thanks,

I followed the steps again, and I just faced a problem with ntp.
I talked with Techops here to first solve this problem,  I'm still waiting for some reply.

**Comment by bwgpro** [comment]
@varac Had the same NTP problem and I was wondering if we could do something so things won't break because of NTP, can you think of any issue with that approach?

**Comment by bwgpro** [comment]
@varac to give more information, the ntpdate command is run inside the vagrant box, I tried running that on a VPN (where NTP is not blocked) but that was unsuccessful too.
The host and the guest are not sharing the network, the guest never uses the VPN. I researched that a little and found out that the Vagrantfile already has the line people say would fix the network sharing issue but that was not enough in this case.

Please ping me if you need more info or want help fixing this

**Comment by bwgpro** [comment]
I kinda validated this as part of trying to fix #101.
The only problem we still have is the "must restart apache2 after deploy" that is not a new thing and I believe doesn't make sense in this context.

**Comment by varac** [comment]
@neissi please try to stress the importance of allowing ntp with Techops.
It important because all machines should have the same time, otherwise things *will* break at other places. we made this a hard requirement because we rely on certificates in multiple places that can falsely appear expired when the machine as a not-synced time.

**Comment by varac** [comment]
here's the leap_cli bug for dealing with NTP errors: https://leap.se/code/issues/6528

**Comment by bwgpro** [comment]
The only outstanding issue is tapicero, I am dealing with that on the #101, so I think we can close this one

**Comment by varac** [comment]
waiting on #101
