### ISSUE TITLE
[leap] Couchdb >=1.3 uses pbkdf2 as pw hashing algorhythm

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-platform#97]
see https://leap.se/code/issues/7120 for details

**Comment by bwgpro** [comment]
I looked through at the leap issue on that, but the problem is not clear.

Does that mean we have to change hashing algorithm? That we have to change the default couchdb algorithm? Could you clarify it @varac, what is the problem with that?

**Comment by varac** [comment]
@bwgpro: It's the admin pw for accessing couchdb which is hashed with a different algor. since v1.3.
So only leap_platform is affected, because we hash it there to configure admin couchch access.
Does this make is clearer ?

**Comment by varac** [comment]
waiting for https://gitlab.com/leap/platform/merge_requests/53 to get merged

**Comment by varac** [comment]
merged into leap_platform:develop. 
can be QA'd together with #91
