### ISSUE TITLE
Upgrade Wazokazi.is and dev.pixelated to 0.7.0

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-platform#99]
when the useragent works fine with try.pix and unstable.pix (which were upgraded today)

**Comment by varac** [comment]
i deployed lastest leap_platform master branch to dev.pixelated-project.org, containing platform 0.7 release

**Comment by varac** [comment]
i propose that someone else deploys to wazokazi.is in order to spread the knowledge.

**Comment by cz8s** [comment]
wazokazi works. would have been nice to just log in to wazokazi after upgrade. We would have discovered that wazokazi was not working some days earlier

**Comment by cz8s** [comment]
dev works
